### PR TITLE
Add docker-compose.yml necessary to spin up a working Syspass instance.

### PR DESCRIPTION
**Pull request by 9numbernine9**

### CODE REVIEW

**Comment by mymasse** [comment]
If you run this docker-compose from the repo location (which I think it needs to) won't it create all the volumes in the repo folder? Shouldn't all the volumes be in the gitignore in that case. I would suggest creating a volumes folder to store all the docker volume and ignore it for git.

**Review by mymasse — COMMENTED** [review]
If you run this docker-compose from the repo location (which I think it needs to) won't it create all the volumes in the repo folder? Shouldn't all the volumes be in the gitignore in that case. I would suggest creating a volumes folder to store all the docker volume and ignore it for git.

**Review by mymasse — CHANGES_REQUESTED** [review]
Please look at my comment regarding volumes

**Comment by 9numbernine9** [comment]
@mymasse No, the volumes don't get created in the local directory - the volumes are only used to share data between the containers and not the host. :)

Starting with a fresh clone of the repo, adding the `.env` files, and running `docker-compose up`, the resulting directory structure looks like this:
```
root@syspass-docker-test:~/syspass # find . | grep -v './.git'
.
./nginx
./nginx/templates
./nginx/templates/nginx.tmpl
./docker-compose.yml
./LICENSE
./README.md
./syspass
./syspass/.empty
./syspass/syspass-variables.env
./mariadb
./mariadb/.empty
./mariadb/mariadb-variables.env
```

**Review by mymasse — APPROVED** [review]
LGTM

**Pull request merged**
